version: '{build}'
image: Visual Studio 2017
environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  CAKE_VERSION: 0.23.0
test: off
deploy: off
build_script:
- cmd: >-
    mkdir tools

    @echo ^<Project Sdk="Microsoft.NET.Sdk"^>^<PropertyGroup^>^<OutputType^>Exe^</OutputType^>^<TargetFramework^>netcoreapp2.0^</TargetFramework^>^</PropertyGroup^>^</Project^> > tools\tools.csproj

    dotnet add tools/tools.csproj package Cake.CoreCLR -v %CAKE_VERSION% --package-directory tools/Cake.CoreCLR.%CAKE_VERSION%

    dotnet tools/Cake.CoreCLR.%CAKE_VERSION%/cake.coreclr/%CAKE_VERSION%/Cake.dll build.cake -target="Default" -configuration="Release"
